# Generated by Django 6.0.6 on 2026-06-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='region',
        ),
    ]
